### PR TITLE
Maintenance: kirbyup & Prettier

### PR DESCRIPTION
**Pull request by johannschopplich**
Hey there, it's me again. With some maintenance.

- Simplify build process.
  - Replace Gulp and Rollup with single-line [kirbyup](https://github.com/johannschopplich/kirbyup) setup. kirbyup is inteded to replace the old Parcel setups as well and will be soon merged into the official Kirby docs.
- Formatting with Prettier.
- Actually track `index.js` out file. It was excluded by the `.gitignore` before, but I don't know, why.

Hope you like it.

### CODE REVIEW

**Comment by rasteiner** [comment]
I often prefer to keep build files and dependencies out of source repos. The dist files are built by a CI server and then go into https://github.com/rasteiner-dist/k3-query-field/ from where packagist gets its package. To keep the separation clear and explicit I ignore index.js/css and node_modules in git. 

This way composer installs don't have to download development stuff. 

I'll test kirbyup in my (and CIs) environment as soon as I get a moment and let you know :)

**Comment by johannschopplich** [comment]
I see! With [kirbyup](https://github.com/johannschopplich/kirbyup) in conjunction with `npx`, you won't have to keep an eye out for the `node_modules` folder anymore. (Maybe relevant to you for future projects. 😉)

Smart idea with keeping the dist files out of the repo. I have reverted that change. 

Thanks! Feedback on kirbyup much appreciated.

**Comment by rasteiner** [comment]
Oh, I normally put "package-lock.json" into the repo to ensure reproducible builds

Thanks :)

----

edit: ignore this comment, I've read the commit wrong. You have actually added the file, not removed it 👍

**Comment by johannschopplich** [comment]
I've also added ESLint to catch common errors. Defaults to Vue recommended linting rules. Have fixed them as well.

**Pull request closed without merging**
